# Replace the text below to customize your site
site_name: Myrto Eirini Pappa - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Myrto Eirini Pappa
copyright: Copyleft 2021 "Student Name" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - welcome: index.md
  - about: about/me.md
  - master project: master project/master project.md
  - reflections:
    - term 1:
      - aows: reflections/term1/aows/02-Atlas of Weak Signals.md
      - bootcamp: reflections/term1/bootcamp/01-Bootcamp.md
      - bio & agri zero: reflections/term1/bio&agrizero/03-Bio & Agri Zero.md
      - community engagement: reflections/term1/community engagement/community engagement.md
      - design studio i:
        - the roles of prototyping: reflections/term1/design studio i/prototyping roles/the roles of prototyping.md
        - workspace: reflections/term1/design studio i/workspace/my workspace.md
        - collective interventions: reflections/term1/design studio i/collective interventions/collective interventions.md
        - communication: reflections/term1/design studio i/communication/communication.md
        - learnings: reflections/term1/design studio i/learnings/learnings.md
      - extended intelligences: reflections/term1/extended intelligences/extended intelligences.md
      - living with your own ideas: reflections/term1/living with your own ideas/living with your own ideas.md
      - tech beyond the myth: reflections/term1/tech beyond the myth/tech beyond the myth.md
    - term 2:
      - billion seconds: reflections/term2/billion seconds/billion seconds.md
      - remixing materials: reflections/term2/remixing materials/remixing materials.md
      - design studio ii: reflections/term2/design studio ii/design studio ii.md
      - prototyping: 
        - music with arduino: reflections/term2/prototyping/music with arduino/music.md
        - parametric croissant: reflections/term2/prototyping/parametric croissant/parametric croissant.md
        - generative design: reflections/term2/prototyping/generative design/generative design.md
        - laser cutting: reflections/term2/prototyping/laser cutting/laser.md
        - inputs & outputs: reflections/term2/prototyping/inputs & outputs/inputsoutputs.md
        - microchallenge i: reflections/term2/prototyping/microchallenge i/microchallenge i.md
        - networking: reflections/term2/prototyping/networking/networking.md
        - 3d printing: reflections/term2/prototyping/3d printing/3d printing.md
        - interfaces: reflections/term2/prototyping/interfaces/interfaces.md
        - cnc: reflections/term2/prototyping/cnc/cnc.md
        - measuring the world: reflections/term2/measuring the world/cnc/measuring the world.md
        - microchallenge ii: reflections/term2/prototyping/microchallenge ii/microchallenge ii.md
      - communicating ideas: reflections/term2/communicating ideas/communicating ideas.md
      - making sense and meaning: reflections/term2/making sense/making sense.md
    - term 3: 
      - distributed design: reflections/term3/distributed design/distributed design.md
      - design studio iii: reflections/term3/design studio iii/design studio iii.md
      - design ethics: reflections/term3/design ethics/design ethics.md
  - process:
    - exploring: process/exploring/exploring.md
    - narrating: process/narrating/narrating.md
    - practising: process/practising/practising.md
extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/myrt.is/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono

  logo: images/holo.png
  favicon: images/holo.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
